services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db-1
      - db-2
      - db-3
    environment:
      - DB_1_URL=postgres://user:password@db-1:5432/edudb
      - DB_2_URL=postgres://user:password@db-2:5432/edudb
      - DB_3_URL=postgres://user:password@db-3:5432/edudb
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./next.config.js
          action: rebuild
        - path: .
          target: /app
          action: sync

  db-1:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: edudb
    ports:
      - '5432:5432'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/1_init.sql
      - ./db/db_1.sql:/docker-entrypoint-initdb.d/2_data.sql

  db-2:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: edudb
    ports:
      - '5433:5432'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/1_init.sql
      - ./db/db_2.sql:/docker-entrypoint-initdb.d/2_data.sql

  db-3:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: edudb
    ports:
      - '5434:5432'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/1_init.sql
      - ./db/db_3.sql:/docker-entrypoint-initdb.d/2_data.sql
